### Criar cliente
POST http://localhost:3333/clientes
Content-Type: application/json

{
  "nome": "Maria",
  "documento": "12345678901",
  "email": "maria@email.com",
  "telefone": "11999999999",
  "endereco": "Rua A, 123"
}



### Listar todos os clientes
GET http://localhost:3333/clientes
Content-Type: application/json








### Buscar cliente por ID
GET http://localhost:3333/clientes/6975331f40ee5a001f3869a0
Content-Type: application/json




### Atualizar cliente
PUT http://localhost:3333/clientes/6975331f40ee5a001f3869a0
Content-Type: application/json

{
  "nome": "Cliente Atualizado",
  "telefone": "11988888888"
}

### Deletar cliente
DELETE http://localhost:3333/clientes/6975331f40ee5a001f3869a0
Content-Type: application/json

//=========================================================================
//parte das notas                                                         =
//=================================-=-=-=-=-=-=-=-=-=-=-=-==-=-===-===-=-==





### Criar nota fiscal com itens
POST http://localhost:3333/notas
Content-Type: application/json

{
  "cliente":"6975377a40ee5a001f3869a6",
  "tipo": "SERVICO",
  "descricao": "Serviços prestados",
  "itens": [
    {
      "descricao": "Desenvolvimento backend",
      "quantidade": 1,
      "valorUnitario": 150
    },
    {
      "descricao": "Configuração servidor",
      "quantidade": 2,
      "valorUnitario": 250
    }
  ]
}


### Listar notas fiscais
GET http://localhost:3333/notas


### Buscar nota por ID
GET http://localhost:3333/notas/69765ef2a6ba0f4aab7a6e03




### Cancelar nota fiscal
PUT http://localhost:3333/notas/69765ef2a6ba0f4aab7a6e03/cancelar


### Atualizar nota
PUT http://localhost:3333/notas/6976d1c85a1ed47ef1a6256b
Content-Type: application/json

{
  "descricao": "Serviços autonomo",
  "itens": [
    {
      "descricao": "Serviços atualizados",
      "quantidade": 1,
      "valorUnitario": 1250
    },
    {
      "descricao": "Configuração servidor e paginação",
      "quantidade": 12,
      "valorUnitario": 2000
    }
  ]
}


### deletar notas
DELETE http://localhost:3333/notas/69765ef2a6ba0f4aab7a6e03
Content-Type: application/json



### Todas as notas
GET http://localhost:3333/notas

### Filtro por status
GET http://localhost:3333/notas?status=EMITIDA

### Filtro por cliente
GET http://localhost:3333/notas?cliente=6975377a40ee5a001f3869a6

### Filtro por tipo
GET http://localhost:3333/notas?tipo=SERVICO

### Filtro por período
GET http://localhost:3333/notas?dataInicio=2026-01-01&dataFim=2026-01-31



### teste
GET http://localhost:3333/notas?page=1&limit=5

###
GET http://localhost:3333/notas?page=2&limit=5

###
GET http://localhost:3333/notas?status=EMITIDA&page=1&limit=3

### valor crescente
GET http://localhost:3333/notas?sortBy=valorTotal&order=asc

### data de emissão
GET http://localhost:3333/notas?sortBy=dataEmissao&order=desc

### filtros
GET http://localhost:3333/notas?status=EMITIDA&sortBy=valorTotal&order=desc&page=1&limit=3



### testes de faturamento
GET http://localhost:3333/notas/relatorios/faturamento

###
GET http://localhost:3333/notas/relatorios/faturamento?dataInicio=2026-01-01&dataFim=2026-01-31

### relatorio cliente
GET http://localhost:3333/notas/relatorios/por-cliente

### emitidas canceladas
GET http://localhost:3333/notas/relatorios/status
